from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
import csv
def read_data(file_path):
    with open(file_path, newline='') as file:
        reader = csv.DictReader(file)
        data = [row for row in reader]
    return data
def generate_pdf(data, output_path):
    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, " Student Score Report")
    c.setFont("Helvetica", 12)
    y = height - 100
    for row in data:
        name = row["Name"]
        score = row["Score"]
        c.drawString(60, y, f"{name} scored {score}")
        y -= 20
    c.drawString(50, 40, "Generated by Python ")
    c.save()
data = read_data("data.txt")
generate_pdf(data, "report.pdf")
print(" Report generated: report.pdf")
